---
- name: "Ensure mount points paths match their defined state."
  when: aspects_autofs_mount_point_paths is defined
  file:
    state: "{{ item.value.state }}"
    path: "{{ item.value.path }}"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
  with_dict: "{{ aspects_autofs_mount_point_paths }}"
  tags:
    - aspects_autofs

- name: "Set /etc/auto.master template"
  template:
    src: "etc-auto.master.j2"
    dest: "/etc/auto.master"
    owner: root
    group: root
    mode: "0644"
  notify: restart autofs
  tags:
    - aspects_autofs

- name: "Set /etc/auto.misc template"
  template:
    src: "etc-auto.misc.j2"
    dest: "/etc/auto.misc"
    owner: root
    group: root
    mode: "0644"
  notify: restart autofs
  tags:
    - aspects_autofs